import React from 'react';
import { FooterResponsive } from '@catho-private/catho-components';

const contract = [
  {
    label: 'Candidates',
    items: [
      {
        url: 'http://google.com',
        label: 'Vagas de home office',
        dataGtmEventName: 'interaction:normal-metric',
        dataGtmEventCategory: 'catho',
        dataGtmEventLabel: 'link:zhaopin',
        dataGtmEventAction: 'novo-footer:parceiros-internacionais',
      },
      {
        url: 'http://google.com',
        label: 'O que é home office?',
        dataGtmEventName: 'interaction:normal-metric',
        dataGtmEventCategory: 'catho',
        dataGtmEventLabel: 'link:zhaopin',
        dataGtmEventAction: 'novo-footer:parceiros-internacionais',
      },
      {
        url: 'http://google.com',
        label: 'Como fazer uma carta de demissão?',
        dataGtmEventName: 'interaction:normal-metric',
        dataGtmEventCategory: 'catho',
        dataGtmEventLabel: 'link:zhaopin',
        dataGtmEventAction: 'novo-footer:parceiros-internacionais',
      },
      {
        url: 'http://google.com',
        label: 'Como fazer um currículo sem experiência e sem ensino superior',
        dataGtmEventName: 'interaction:normal-metric',
        dataGtmEventCategory: 'catho',
        dataGtmEventLabel: 'link:zhaopin',
        dataGtmEventAction: 'novo-footer:parceiros-internacionais',
      },
      {
        url: 'http://google.com',
        label: 'o que é inteligência emocional',
        dataGtmEventName: 'interaction:normal-metric',
        dataGtmEventCategory: 'catho',
        dataGtmEventLabel: 'link:zhaopin',
        dataGtmEventAction: 'novo-footer:parceiros-internacionais',
      },
      {
        url: 'http://google.com',
        label: 'Qual é a diferença entre currículo e carta de apresentação?',
        dataGtmEventName: 'interaction:normal-metric',
        dataGtmEventCategory: 'catho',
        dataGtmEventLabel: 'link:zhaopin',
        dataGtmEventAction: 'novo-footer:parceiros-internacionais',
      },
      {
        url: 'http://google.com',
        label: 'Estresse no trabalho: por que acontece e como lidar',
        dataGtmEventName: 'interaction:normal-metric',
        dataGtmEventCategory: 'catho',
        dataGtmEventLabel: 'link:zhaopin',
        dataGtmEventAction: 'novo-footer:parceiros-internacionais',
      },
      {
        url: 'http://google.com',
        label: '5 característica de um bom líder',
        dataGtmEventName: 'interaction:normal-metric',
        dataGtmEventCategory: 'catho',
        dataGtmEventLabel: 'link:zhaopin',
        dataGtmEventAction: 'novo-footer:parceiros-internacionais',
      },
      {
        url: 'http://google.com',
        label: 'O que falar e o que não falar em uma entrevista de emprego',
        dataGtmEventName: 'interaction:normal-metric',
        dataGtmEventCategory: 'catho',
        dataGtmEventLabel: 'link:zhaopin',
        dataGtmEventAction: 'novo-footer:parceiros-internacionais',
      },
      {
        url: 'http://google.com',
        label: 'Como montar um bom currículo?',
        dataGtmEventName: 'interaction:normal-metric',
        dataGtmEventCategory: 'catho',
        dataGtmEventLabel: 'link:zhaopin',
        dataGtmEventAction: 'novo-footer:parceiros-internacionais',
      },
    ],
  },
  {
    label: 'Companies',
    items: [
      {
        url: 'http://google.com',
        label: 'O que é home office?',
        dataGtmEventName: 'interaction:normal-metric',
        dataGtmEventCategory: 'catho',
        dataGtmEventLabel: 'link:zhaopin',
        dataGtmEventAction: 'novo-footer:parceiros-internacionais',
      },
      {
        url: 'http://google.com',
        label: 'Como fazer uma carta de demissão?',
        dataGtmEventName: 'interaction:normal-metric',
        dataGtmEventCategory: 'catho',
        dataGtmEventLabel: 'link:zhaopin',
        dataGtmEventAction: 'novo-footer:parceiros-internacionais',
      },
      {
        url: 'http://google.com',
        label: 'Vagas de home office',
        dataGtmEventName: 'interaction:normal-metric',
        dataGtmEventCategory: 'catho',
        dataGtmEventLabel: 'link:zhaopin',
        dataGtmEventAction: 'novo-footer:parceiros-internacionais',
      },

      {
        url: 'http://google.com',
        label: 'Como fazer um currículo sem experiência e sem ensino superior',
        dataGtmEventName: 'interaction:normal-metric',
        dataGtmEventCategory: 'catho',
        dataGtmEventLabel: 'link:zhaopin',
        dataGtmEventAction: 'novo-footer:parceiros-internacionais',
      },
      {
        url: 'http://google.com',
        label: 'o que é inteligência emocional',
        dataGtmEventName: 'interaction:normal-metric',
        dataGtmEventCategory: 'catho',
        dataGtmEventLabel: 'link:zhaopin',
        dataGtmEventAction: 'novo-footer:parceiros-internacionais',
      },
      {
        url: 'http://google.com',
        label: 'Estresse no trabalho: por que acontece e como lidar',
        dataGtmEventName: 'interaction:normal-metric',
        dataGtmEventCategory: 'catho',
        dataGtmEventLabel: 'link:zhaopin',
        dataGtmEventAction: 'novo-footer:parceiros-internacionais',
      },
      {
        url: 'http://google.com',
        label: '5 característica de um bom líder',
        dataGtmEventName: 'interaction:normal-metric',
        dataGtmEventCategory: 'catho',
        dataGtmEventLabel: 'link:zhaopin',
        dataGtmEventAction: 'novo-footer:parceiros-internacionais',
      },
      {
        url: 'http://google.com',
        label: 'Qual é a diferença entre currículo e carta de apresentação?',
        dataGtmEventName: 'interaction:normal-metric',
        dataGtmEventCategory: 'catho',
        dataGtmEventLabel: 'link:zhaopin',
        dataGtmEventAction: 'novo-footer:parceiros-internacionais',
      },

      {
        url: 'http://google.com',
        label: 'O que falar e o que não falar em uma entrevista de emprego',
        dataGtmEventName: 'interaction:normal-metric',
        dataGtmEventCategory: 'catho',
        dataGtmEventLabel: 'link:zhaopin',
        dataGtmEventAction: 'novo-footer:parceiros-internacionais',
      },
      {
        url: 'http://google.com',
        label: 'Como montar um bom currículo?',
        dataGtmEventName: 'interaction:normal-metric',
        dataGtmEventCategory: 'catho',
        dataGtmEventLabel: 'link:zhaopin',
        dataGtmEventAction: 'novo-footer:parceiros-internacionais',
      },
    ],
  },
  {
    label: 'Education',
    items: [
      {
        url: 'http://google.com',
        label: 'Estresse no trabalho: por que acontece e como lidar',
        dataGtmEventName: 'interaction:normal-metric',
        dataGtmEventCategory: 'catho',
        dataGtmEventLabel: 'link:zhaopin',
        dataGtmEventAction: 'novo-footer:parceiros-internacionais',
      },
      {
        url: 'http://google.com',
        label: '5 característica de um bom líder',
        dataGtmEventName: 'interaction:normal-metric',
        dataGtmEventCategory: 'catho',
        dataGtmEventLabel: 'link:zhaopin',
        dataGtmEventAction: 'novo-footer:parceiros-internacionais',
      },
      {
        url: 'http://google.com',
        label: 'O que falar e o que não falar em uma entrevista de emprego',
        dataGtmEventName: 'interaction:normal-metric',
        dataGtmEventCategory: 'catho',
        dataGtmEventLabel: 'link:zhaopin',
        dataGtmEventAction: 'novo-footer:parceiros-internacionais',
      },
      {
        url: 'http://google.com',
        label: 'Como montar um bom currículo?',
        dataGtmEventName: 'interaction:normal-metric',
        dataGtmEventCategory: 'catho',
        dataGtmEventLabel: 'link:zhaopin',
        dataGtmEventAction: 'novo-footer:parceiros-internacionais',
      },
      {
        url: 'http://google.com',
        label: 'Vagas de home office',
        dataGtmEventName: 'interaction:normal-metric',
        dataGtmEventCategory: 'catho',
        dataGtmEventLabel: 'link:zhaopin',
        dataGtmEventAction: 'novo-footer:parceiros-internacionais',
      },
      {
        url: 'http://google.com',
        label: 'O que é home office?',
        dataGtmEventName: 'interaction:normal-metric',
        dataGtmEventCategory: 'catho',
        dataGtmEventLabel: 'link:zhaopin',
        dataGtmEventAction: 'novo-footer:parceiros-internacionais',
      },
      {
        url: 'http://google.com',
        label: 'Como fazer uma carta de demissão?',
        dataGtmEventName: 'interaction:normal-metric',
        dataGtmEventCategory: 'catho',
        dataGtmEventLabel: 'link:zhaopin',
        dataGtmEventAction: 'novo-footer:parceiros-internacionais',
      },
      {
        url: 'http://google.com',
        label: 'Como fazer um currículo sem experiência e sem ensino superior',
        dataGtmEventName: 'interaction:normal-metric',
        dataGtmEventCategory: 'catho',
        dataGtmEventLabel: 'link:zhaopin',
        dataGtmEventAction: 'novo-footer:parceiros-internacionais',
      },
      {
        url: 'http://google.com',
        label: 'o que é inteligência emocional',
        dataGtmEventName: 'interaction:normal-metric',
        dataGtmEventCategory: 'catho',
        dataGtmEventLabel: 'link:zhaopin',
        dataGtmEventAction: 'novo-footer:parceiros-internacionais',
      },
      {
        url: 'http://google.com',
        label: 'Qual é a diferença entre currículo e carta de apresentação?',
        dataGtmEventName: 'interaction:normal-metric',
        dataGtmEventCategory: 'catho',
        dataGtmEventLabel: 'link:zhaopin',
        dataGtmEventAction: 'novo-footer:parceiros-internacionais',
      },
    ],
  },
  {
    label: 'Privates',
    items: [
      {
        url: 'http://google.com',
        label: 'Vagas de home office',
        dataGtmEventName: 'interaction:normal-metric',
        dataGtmEventCategory: 'catho',
        dataGtmEventLabel: 'link:zhaopin',
        dataGtmEventAction: 'novo-footer:parceiros-internacionais',
      },
      {
        url: 'http://google.com',
        label: 'O que é home office?',
        dataGtmEventName: 'interaction:normal-metric',
        dataGtmEventCategory: 'catho',
        dataGtmEventLabel: 'link:zhaopin',
        dataGtmEventAction: 'novo-footer:parceiros-internacionais',
      },
      {
        url: 'http://google.com',
        label: 'Como fazer uma carta de demissão?',
        dataGtmEventName: 'interaction:normal-metric',
        dataGtmEventCategory: 'catho',
        dataGtmEventLabel: 'link:zhaopin',
        dataGtmEventAction: 'novo-footer:parceiros-internacionais',
      },
      {
        url: 'http://google.com',
        label: 'Como fazer um currículo sem experiência e sem ensino superior',
        dataGtmEventName: 'interaction:normal-metric',
        dataGtmEventCategory: 'catho',
        dataGtmEventLabel: 'link:zhaopin',
        dataGtmEventAction: 'novo-footer:parceiros-internacionais',
      },
      {
        url: 'http://google.com',
        label: 'o que é inteligência emocional',
        dataGtmEventName: 'interaction:normal-metric',
        dataGtmEventCategory: 'catho',
        dataGtmEventLabel: 'link:zhaopin',
        dataGtmEventAction: 'novo-footer:parceiros-internacionais',
      },
      {
        url: 'http://google.com',
        label: 'Qual é a diferença entre currículo e carta de apresentação?',
        dataGtmEventName: 'interaction:normal-metric',
        dataGtmEventCategory: 'catho',
        dataGtmEventLabel: 'link:zhaopin',
        dataGtmEventAction: 'novo-footer:parceiros-internacionais',
      },
      {
        url: 'http://google.com',
        label: 'Estresse no trabalho: por que acontece e como lidar',
        dataGtmEventName: 'interaction:normal-metric',
        dataGtmEventCategory: 'catho',
        dataGtmEventLabel: 'link:zhaopin',
        dataGtmEventAction: 'novo-footer:parceiros-internacionais',
      },
      {
        url: 'http://google.com',
        label: '5 característica de um bom líder',
        dataGtmEventName: 'interaction:normal-metric',
        dataGtmEventCategory: 'catho',
        dataGtmEventLabel: 'link:zhaopin',
        dataGtmEventAction: 'novo-footer:parceiros-internacionais',
      },
      {
        url: 'http://google.com',
        label: 'O que falar e o que não falar em uma entrevista de emprego',
        dataGtmEventName: 'interaction:normal-metric',
        dataGtmEventCategory: 'catho',
        dataGtmEventLabel: 'link:zhaopin',
        dataGtmEventAction: 'novo-footer:parceiros-internacionais',
      },
      {
        url: 'http://google.com',
        label: 'Como montar um bom currículo?',
        dataGtmEventName: 'interaction:normal-metric',
        dataGtmEventCategory: 'catho',
        dataGtmEventLabel: 'link:zhaopin',
        dataGtmEventAction: 'novo-footer:parceiros-internacionais',
      },
    ],
  },
  {
    label: 'Extra',
    items: [
      {
        url: 'http://google.com',
        label: 'Vagas de home office',
        dataGtmEventName: 'interaction:normal-metric',
        dataGtmEventCategory: 'catho',
        dataGtmEventLabel: 'link:zhaopin',
        dataGtmEventAction: 'novo-footer:parceiros-internacionais',
      },
      {
        url: 'http://google.com',
        label: 'O que é home office?',
        dataGtmEventName: 'interaction:normal-metric',
        dataGtmEventCategory: 'catho',
        dataGtmEventLabel: 'link:zhaopin',
        dataGtmEventAction: 'novo-footer:parceiros-internacionais',
      },
      {
        url: 'http://google.com',
        label: 'Como fazer uma carta de demissão?',
        dataGtmEventName: 'interaction:normal-metric',
        dataGtmEventCategory: 'catho',
        dataGtmEventLabel: 'link:zhaopin',
        dataGtmEventAction: 'novo-footer:parceiros-internacionais',
      },
      {
        url: 'http://google.com',
        label: 'Como fazer um currículo sem experiência e sem ensino superior',
        dataGtmEventName: 'interaction:normal-metric',
        dataGtmEventCategory: 'catho',
        dataGtmEventLabel: 'link:zhaopin',
        dataGtmEventAction: 'novo-footer:parceiros-internacionais',
      },
      {
        url: 'http://google.com',
        label: 'o que é inteligência emocional',
        dataGtmEventName: 'interaction:normal-metric',
        dataGtmEventCategory: 'catho',
        dataGtmEventLabel: 'link:zhaopin',
        dataGtmEventAction: 'novo-footer:parceiros-internacionais',
      },
      {
        url: 'http://google.com',
        label: 'Qual é a diferença entre currículo e carta de apresentação?',
        dataGtmEventName: 'interaction:normal-metric',
        dataGtmEventCategory: 'catho',
        dataGtmEventLabel: 'link:zhaopin',
        dataGtmEventAction: 'novo-footer:parceiros-internacionais',
      },
      {
        url: 'http://google.com',
        label: 'Estresse no trabalho: por que acontece e como lidar',
        dataGtmEventName: 'interaction:normal-metric',
        dataGtmEventCategory: 'catho',
        dataGtmEventLabel: 'link:zhaopin',
        dataGtmEventAction: 'novo-footer:parceiros-internacionais',
      },
      {
        url: 'http://google.com',
        label: '5 característica de um bom líder',
        dataGtmEventName: 'interaction:normal-metric',
        dataGtmEventCategory: 'catho',
        dataGtmEventLabel: 'link:zhaopin',
        dataGtmEventAction: 'novo-footer:parceiros-internacionais',
      },
      {
        url: 'http://google.com',
        label: 'O que falar e o que não falar em uma entrevista de emprego',
        dataGtmEventName: 'interaction:normal-metric',
        dataGtmEventCategory: 'catho',
        dataGtmEventLabel: 'link:zhaopin',
        dataGtmEventAction: 'novo-footer:parceiros-internacionais',
      },
      {
        url: 'http://google.com',
        label: 'Como montar um bom currículo?',
        dataGtmEventName: 'interaction:normal-metric',
        dataGtmEventCategory: 'catho',
        dataGtmEventLabel: 'link:zhaopin',
        dataGtmEventAction: 'novo-footer:parceiros-internacionais',
      },
    ],
  },
  {
    label: 'Others',
    items: [
      {
        url: 'http://google.com',
        label: 'Vagas de home office',
        dataGtmEventName: 'interaction:normal-metric',
        dataGtmEventCategory: 'catho',
        dataGtmEventLabel: 'link:zhaopin',
        dataGtmEventAction: 'novo-footer:parceiros-internacionais',
      },
      {
        url: 'http://google.com',
        label: 'O que é home office?',
        dataGtmEventName: 'interaction:normal-metric',
        dataGtmEventCategory: 'catho',
        dataGtmEventLabel: 'link:zhaopin',
        dataGtmEventAction: 'novo-footer:parceiros-internacionais',
      },
      {
        url: 'http://google.com',
        label: 'Como fazer uma carta de demissão?',
        dataGtmEventName: 'interaction:normal-metric',
        dataGtmEventCategory: 'catho',
        dataGtmEventLabel: 'link:zhaopin',
        dataGtmEventAction: 'novo-footer:parceiros-internacionais',
      },
      {
        url: 'http://google.com',
        label: 'Como fazer um currículo sem experiência e sem ensino superior',
        dataGtmEventName: 'interaction:normal-metric',
        dataGtmEventCategory: 'catho',
        dataGtmEventLabel: 'link:zhaopin',
        dataGtmEventAction: 'novo-footer:parceiros-internacionais',
      },
      {
        url: 'http://google.com',
        label: 'o que é inteligência emocional',
        dataGtmEventName: 'interaction:normal-metric',
        dataGtmEventCategory: 'catho',
        dataGtmEventLabel: 'link:zhaopin',
        dataGtmEventAction: 'novo-footer:parceiros-internacionais',
      },
      {
        url: 'http://google.com',
        label: 'Qual é a diferença entre currículo e carta de apresentação?',
        dataGtmEventName: 'interaction:normal-metric',
        dataGtmEventCategory: 'catho',
        dataGtmEventLabel: 'link:zhaopin',
        dataGtmEventAction: 'novo-footer:parceiros-internacionais',
      },
      {
        url: 'http://google.com',
        label: 'Estresse no trabalho: por que acontece e como lidar',
        dataGtmEventName: 'interaction:normal-metric',
        dataGtmEventCategory: 'catho',
        dataGtmEventLabel: 'link:zhaopin',
        dataGtmEventAction: 'novo-footer:parceiros-internacionais',
      },
      {
        url: 'http://google.com',
        label: '5 característica de um bom líder',
        dataGtmEventName: 'interaction:normal-metric',
        dataGtmEventCategory: 'catho',
        dataGtmEventLabel: 'link:zhaopin',
        dataGtmEventAction: 'novo-footer:parceiros-internacionais',
      },
      {
        url: 'http://google.com',
        label: 'O que falar e o que não falar em uma entrevista de emprego',
        dataGtmEventName: 'interaction:normal-metric',
        dataGtmEventCategory: 'catho',
        dataGtmEventLabel: 'link:zhaopin',
        dataGtmEventAction: 'novo-footer:parceiros-internacionais',
      },
      {
        url: 'http://google.com',
        label: 'Como montar um bom currículo?',
        dataGtmEventName: 'interaction:normal-metric',
        dataGtmEventCategory: 'catho',
        dataGtmEventLabel: 'link:zhaopin',
        dataGtmEventAction: 'novo-footer:parceiros-internacionais',
      },
    ],
  },
];

const FooterTagsList = () => (
  <FooterResponsive
    gtmPrefix="B2C-google-tag-prefix"
    tagsListContent={contract}
  />
);

export default FooterTagsList;
